### ISSUE TITLE
Code related issues

### ISSUE THREAD

**Issue by Arican-Lee** [wooseoklee4/AP-BSN#1]
Hello, I want to ask how to solve this problem.When I ran the train.py, an error is reported here.
![7aa775baf85b93095423785f64dca9b](https://user-images.githubusercontent.com/98862990/160113688-7e2c29e1-c6a9-4bc9-99da-f345731627f3.png)

Could you provide the dataset of DND. I am a freshman and I can't register because there is no relevant Google Scholar Profile,My email address is 958244227@qq.com

**Comment by wooseoklee4** [comment]
Hi, if you want to run training code, you should add argument for configuration file. There are serveral instructions and examples at README.md for training also for test code.
And if you have troubles to run my code due to dataset, I recommand to run code using the SIDD or NIND dataset first.

**Comment by Arican-Lee** [comment]
Hello, I have followed the serveral instruction and examples at README.md for training to  add argument for configuration file. But the new problem appears.
"AttributeError: 'Namespace' object has no attribute 'config'"
![1648219468(1)](https://user-images.githubusercontent.com/98862990/160143274-af7e6873-e4dc-4d9c-b057-2c5b4cc9582d.png)
Thank you very much for your help！

**Comment by wooseoklee4** [comment]
I will send you comment via email.

**Comment by Arican-Lee** [comment]
Thank you for your reply
Hello, I have followed the serveral instruction and examples at README.md for training to add argument for configuration file. But the new problem appears.
"AttributeError: 'Namespace' object has no attribute 'config'"





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wooseoklee4/AP-BSN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月26日(星期六) 中午1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wooseoklee4/AP-BSN] Code related issues (Issue #1)





 
I will send you comment via email.
