### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by yashkhurana24** [wooseoklee4/AP-BSN#15]
Hello, I'm trying to denoise a 2D image. I add synthetic noise as follows: 
`np.array(np.random.poisson(0.01 * x / 0.1) / 0.01`
But the model is unable to denoise the image. Can you give some suggestions? 
![Cu K](https://github.com/wooseoklee4/AP-BSN/assets/146676268/c8a4ccfb-cb8a-4ae6-a23e-2d9a6ad4f58b)

**Comment by wooseoklee4** [comment]
Hi, Thank you for your interest in our work

This work is mainly designed to handle real-world noise in RGB domain images, not aiming for synthetic noise.
I recommend other better self-supervised denoising methods that aim more for synthetic noise.

Best
