### ISSUE TITLE
about test dataset

### ISSUE THREAD

**Issue by sunyclj** [wooseoklee4/AP-BSN#2]
Hi,when run 'python test.py -c APBSN_SIDD -g 0 --pretrained APBSN_SIDD.pth --test_img ./00001.png',occur error 'FileNotFoundError: [Errno 2] No such file or directory: './dataset/SIDD/BenchmarkNoisyBlocksSrgb.mat'.What's the reason?Can test data only be SSID data sets?
![image](https://user-images.githubusercontent.com/44860428/163514023-50c3ecac-c650-40fc-b8b4-025b3cf3ef94.png)

**Comment by wooseoklee4** [comment]
Hi, sunyclj.
Thanks for reporting problems while you run the code.
It was a bug while you test a single image without the dataset.
And I fixed that bug and further implemented testing code for entire image folder for convenience.

I pushed the updated code, and thanks you again for reporting bug:)
