### ISSUE TITLE
About experiment results

### ISSUE THREAD

**Issue by HW-VMCL** [wooseoklee4/AP-BSN#3]
Hi, I use SIDD-Medium dataset and get 24,542 cropped images after prepare. Then I run` python train.py -c APBSN_SIDD -g 0` without changing the code as well as the config file. I have trained the code by default setting for several times on RTX 3070Ti Laptop, GTX 1080Ti and Tesla A100. But the performance seems not as good as that mentioned in the paper.
<img width="344" alt="屏幕截图 2022-04-22 151745" src="https://user-images.githubusercontent.com/55520335/164631041-70ca391c-9934-4348-8c0b-f5fecb52d5bc.png">
Moreover, I download the SIDD pretrained model and change the setting in config file to test the model on SIDD_val. Then I run `python test.py -c APBSN_SIDD -g 0 --pretrained APBSN_SIDD.pth`. The result is showed bellow.
<img width="500" alt="屏幕截图 2022-04-22 151634" src="https://user-images.githubusercontent.com/55520335/164630683-a4dd27cf-d2ea-4727-88a6-9f5b24e743a2.png">
I'm confused and want to confirm the experiment setting. Thanks!

**Comment by wooseoklee4** [comment]
Hi, Thanks for asking about our code and method.

In the validation during training, model do test only 64 images of the SIDD validation for simple and fast experiments.
That is reason for the reduced PSNR and SSIM. This can be changed in the config file by replacing '64' to 'None' for 'n_data', or removing the highlighted line. (below image)
![제목 없음](https://user-images.githubusercontent.com/14971561/164768555-b99bdd3e-b026-46b3-be9d-72dce9458aea.png)

Furthermore, you can test your trained model for the entire SIDD validation dataset by changing settings as you did and running `python test.py -c APBSN_SIDD -g 0 -e 20`.
I think you may get similar results with pre-trained one.

Thank you for your issue again :)

**Comment by HW-VMCL** [comment]
OK, I get it now. Thank you for your reply!

**Comment by liuxuuuu** [comment]
> OK, I get it now. Thank you for your reply!

你好兄弟，请问你最后的结果达到论文里差不多的数据了吗，我按照上面说的改，依然是0.877，能帮忙指点一下吗，谢谢
