### ISSUE TITLE
About results on  SIDD benchmark

### ISSUE THREAD

**Issue by HW-VMCL** [wooseoklee4/AP-BSN#4]
Hi, I use the pre-trained model 'APBSN_SIDD.pth' and test it on the SIDD benchmark. I submit the results to the SIDD benchmark website and get 

PSNR_Srgb,SSIM_Srgb,TimeSrgb(s)
36.73,0.932,-1

But  model trained on SIDD Medium dataset gets  35.97/0.925 on the SIDD benchmark as it mentioned in the paper.

**Comment by wooseoklee4** [comment]
Hi, thanks for your issue.

We provide a training example of pre-trained model weight by our code.

Instead, we upload the result images what we used in the main table.
If you need denoised images of SIDD validation or benchmark dataset, please check the recently uploaded link for this.

Thanks.
