### ISSUE TITLE
About model trained on SIDD Medium and inference on SIDD benchmark

### ISSUE THREAD

**Issue by HW-VMCL** [wooseoklee4/AP-BSN#5]
Thanks for your reply！
Furthermore, I train your code on SIDD Medium sRGB dataset, and run `python test.py -c APBSN_SIDD -g 0 -e 20 ` .I pack the results into `SubmitSrgb.mat ` and submit it to the SIDD benchmark website. The results are as follows.
<img width="212" alt="屏幕截图 2022-05-13 135408" src="https://user-images.githubusercontent.com/55520335/168219924-11e96253-ac56-4ca4-a5df-a6c067045410.png">

But I notice that the model trained on SIDD Medium sRGB dataset gets **35.97/0.925** on SIDD benchmark. The model trained on SIDD benchmark in a fully self-supervised fashion gets **36.91/0.931** on SIDD benchmark in the paper.
<img width="401" alt="屏幕截图 2022-05-13 135259" src="https://user-images.githubusercontent.com/55520335/168219795-382424b1-16e5-47d3-9c26-1ebc20e4111e.png">
I have no idea why there's 0.85/0.007 gap when it trained on SIDD Medium and infered on SIDD benchmark.
Thanks for your time and attention again!

**Comment by wooseoklee4** [comment]
We had observed that there is a variation of results due to randomness of training.
While we get better results than what we reported,
but we reported what we initially get and this model was used in all the ablation studies.

Thanks for your interest in our work again :)

**Comment by HW-VMCL** [comment]
OK, thanks for your reply!
